Decision Tree with python


Task: Precision, f1 score, recall 
what is difference between these three?
Which measure is suitable to use ? which measure is useful in which circumtances?


In [1]:
#Precision quantifies the number of positive class predictions that actually belong to the positive class. 
# Recall quantifies the number of positive class predictions made out of all positive examples in the dataset. 
# F-Measure provides a single score that balances both the concerns of precision and recall in one number.

Recall is a metric that quantifies the number of correct positive predictions made out of all positive predictions that could have been made.

Unlike precision that only comments on the correct positive predictions out of all positive predictions, recall provides an indication of missed positive predictions.

Precision: Precision is a metric that measures the accuracy of positive predictions made by a model. It is calculated as the ratio of true positives to the total number of positive predictions (true positives + false positives). Precision is a measure of how many of the positive predictions made by the model are actually correct.

Precision = True Positives / (True Positives + False Positives)

High precision indicates that when the model predicts a positive class, it is likely to be correct. It is suitable when you want to minimize false positives, such as in cases where the cost of a false positive is high.





Use precision when you want to minimize false positives, and it's crucial to be certain that the positive predictions are accurate.

Use recall when you want to minimize false negatives, and it's essential to capture as many positive instances as possible.

In a medical test for a disease, a false negative result would mean that the test falsely indicates a patient does not have the disease when they actually do.

In [2]:
# Decision tree comes in regression and classification as well
#This comes in supervised learning
#import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report



from sklearn.tree import plot_tree

In [3]:
df=sns.load_dataset('diamonds')
df.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [4]:

df = df.drop(['carat'],axis=1)
df = df.drop(['cut'],axis=1)
df = df.drop(['color'],axis=1)
df = df.drop(['depth'],axis=1)
df = df.drop(['table'],axis=1)
df = df.drop(['price'],axis=1)

df.head()



clarity     x     y     z
0     SI2  3.95  3.98  2.43
1     SI1  3.89  3.84  2.31
2     VS1  4.05  4.07  2.31
3     VS2  4.20  4.23  2.63
4     SI2  4.34  4.35  2.75

In [5]:
#features and labels
#x=length in mm, y=width in mm and z=depth in mm

x=df.drop(columns='clarity')
y=df['clarity']

In [6]:
#spliiting
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [7]:
# model building 

dtm=DecisionTreeClassifier()

In [8]:
# Train the model 
dtm.fit(x_train,y_train)

DecisionTreeClassifier()

In [9]:
#testing of model 

y_pred=dtm.predict(x_test)

In [10]:
#Evaluation of model  

#Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Generate a classification report
class_report = classification_report(y_test, y_pred)
print("Classification Report:\n", class_report)

# Generate a confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)


Accuracy: 0.22
Classification Report:
               precision    recall  f1-score   support

          I1       0.09      0.11      0.10       228
          IF       0.08      0.10      0.09       542
         SI1       0.26      0.31      0.28      3848
         SI2       0.26      0.26      0.26      2807
         VS1       0.17      0.17      0.17      2448
         VS2       0.26      0.24      0.25      3673
        VVS1       0.13      0.11      0.12      1085
        VVS2       0.13      0.10      0.11      1551

    accuracy                           0.22     16182
   macro avg       0.17      0.17      0.17     16182
weighted avg       0.22      0.22      0.22     16182

Confusion Matrix:
 [[  26    1   52   68   19   43   10    9]
 [   1   55  113   44   88  118   53   70]
 [  61  139 1176  730  570  779  170  223]
 [  84   66  847  722  327  542   81  138]
 [  25  115  669  363  427  510  157  182]
 [  52  169 1030  567  551  872  197  235]
 [  11   80  260   82  216  209  

Interpretation: precision is 10% that means false positive values are 10%. Recall is 13% mean flase negative values 


In [11]:
plt.figure(figsize=(20,10))
plot_tree(dtm,filled=True)
plt.show()