# 5.Naive Bayes:

- Classification algorithem based on Bayes' theorem, which is used for categorizing data into predefined classes or categories.

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [6]:
student_d=pd.read_csv("student_data.csv") # loading file from computer
student_d.sample(10)
 

gender race/ethnicity parental level of education         lunch  \
563  female        group D                some college  free/reduced   
362  female        group C                some college      standard   
243    male        group E                some college      standard   
859    male        group C          associate's degree  free/reduced   
193    male        group D                some college      standard   
255  female        group E                some college      standard   
56   female        group E          associate's degree      standard   
929  female        group C            some high school  free/reduced   
788    male        group C          associate's degree  free/reduced   
405  female        group C            some high school      standard   

    test preparation course  math score  reading score  writing score  
563               completed          63             80             80  
362                    none          52             58             58  
243                    none          59             51             43  
859                    none          87             73             72  
193               completed          77             62             62  
255                    none          62             73             70  
56                completed          82             85             86  
929                    none          48             56             51  
788                    none          68             65             61  
405                    none          63             73             68

In [8]:
student_d = student_d.drop(['lunch'],axis=1)
student_d = student_d.drop(['parental level of education'],axis=1)
student_d = student_d.drop(['gender'],axis=1)
student_d = student_d.drop(['test preparation course'],axis=1)
student_d.sample(10)

race/ethnicity  math score  reading score  writing score
249        group C          68             60             53
845        group E          90             85             84
406        group B          65             65             63
474        group B          90             90             91
379        group A          66             64             62
405        group C          63             73             68
65         group B          67             64             61
561        group C          63             74             74
289        group E          77             76             77
990        group E          86             81             75

In [10]:
x=student_d.drop(columns='race/ethnicity')
y=student_d['race/ethnicity']

In [11]:

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

# Create a Gaussian Naive Bayes classifier
naive_bayes_classifier = GaussianNB()

# Train the classifier on the training data
naive_bayes_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred = naive_bayes_classifier.predict(X_test)

# Evaluate the classifier's performance
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Generate a classification report
class_report = classification_report(y_test, y_pred)
print("Classification Report:\n", class_report)

# Generate a confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)

Accuracy: 0.30
Classification Report:
               precision    recall  f1-score   support

     group A       0.00      0.00      0.00        32
     group B       0.20      0.17      0.18        60
     group C       0.35      0.57      0.44        92
     group D       0.27      0.21      0.24        80
     group E       0.24      0.28      0.26        36

    accuracy                           0.30       300
   macro avg       0.21      0.24      0.22       300
weighted avg       0.25      0.30      0.26       300

Confusion Matrix:
 [[ 0 12 14  5  1]
 [ 0 10 29 14  7]
 [ 0 14 52 19  7]
 [ 0 10 37 17 16]
 [ 0  3 15  8 10]]


c:\Users\AAA\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\AAA\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\AAA\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modif

# The result for different groups A,B,C,D and E is given. precision, accuracy and f1 score for group A is zero. this result is quite similiar to random forest model result. There is slight change about other groups. 